sudo: required
services:
  - docker

matrix:
    allow_failures:

cache: bundler

install:
    - while sleep 9m; do echo "=====[ $SECONDS seconds still running ]====="; done &
    - docker build -t rock-osdeps/16.04 -f Dockerfile-16.04
            --build-arg PKG_BRANCH="${TRAVIS_BRANCH}"
            --build-arg PKG_PULL_REQUEST="${TRAVIS_PULL_REQUEST}"
            --build-arg PKG_PULL_REQUEST_BRANCH="${TRAVIS_PULL_REQUEST_BRANCH}"
            --build-arg PKG_PULL_REQUEST_SLUG="${TRAVIS_PULL_REQUEST_SLUG}"
            .
    - docker build -t rock-osdeps/18.04 -f Dockerfile-18.04
            --build-arg PKG_BRANCH="${TRAVIS_BRANCH}"
            --build-arg PKG_PULL_REQUEST="${TRAVIS_PULL_REQUEST}"
            --build-arg PKG_PULL_REQUEST_BRANCH="${TRAVIS_PULL_REQUEST_BRANCH}"
            --build-arg PKG_PULL_REQUEST_SLUG="${TRAVIS_PULL_REQUEST_SLUG}"
            .

# overwrite the default build command
script:
    - docker run rock-osdeps/16.04 /bin/bash -c "/home/docker/test_release.sh master-18.01"
    - docker run rock-osdeps/18.04 /bin/bash -c "/home/docker/test_release.sh master-18.09"
    - docker run rock-osdeps/18.04 /bin/bash -c "/home/docker/test_release.sh master-19.06"
    - docker run rock-osdeps/18.04 /bin/bash -c "/home/docker/test_release.sh master-20.01"
    - docker run rock-osdeps/18.04 /bin/bash -c "/home/docker/test_release.sh master-20.06"
