GITHUB: http,ssh
GITHUB_ROOT: https://github.com
GITHUB_ROOT: https://github.com
GITHUB_PUSH_ROOT: https://github.com
GITHUB_PRIVATE_ROOT: https://github.com
ROCK_SELECTED_FLAVOR: master
ROCK_FLAVOR: master
ROCK_BRANCH: master
rtt_target: gnulinux
rtt_corba_implementation: omniorb
typelib_cxx_loader: castxml
cxx11: true
DEB_USE: true
DEB_AUTOMATIC: true
ldgold: true
osdeps_mode: all
USE_OCL: false
GITORIOUS: http,http
GITORIOUS_ROOT: https://git.gitorious.org
GITORIOUS_PUSH_ROOT: https://git.gitorious.org
GITORIOUS_PRIVATE_ROOT: https://git.gitorious.org
apt_dpkg_update: true
USE_PYTHON: false
noninteractive: true
