name: test
on: [push]
jobs:
  unittests:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: current_branch

      - name: Build 16.04
        run: docker build -t rock-osdeps/16.04 -f Dockerfile-16.04 . --build-arg PKG_BRANCH=${{ steps.current_branch.outputs.branch }}

      - name: Build 18.04
        run: docker build -t rock-osdeps/18.04 -f Dockerfile-18.04 . --build-arg PKG_BRANCH=${{ steps.current_branch.outputs.branch }}

      - name: Test-18.01-on-ubuntu:16.04
        run: docker run rock-osdeps/16.04 /bin/bash -c "/home/docker/test_release.sh master-18.01"

      - name: Test-18.09-on-ubuntu:16.04
        run: docker run rock-osdeps/16.04 /bin/bash -c "/home/docker/test_release.sh master-18.09"

      - name: Test-18.09-on-ubuntu:18.04
        run: docker run rock-osdeps/18.04 /bin/bash -c "/home/docker/test_release.sh master-18.09"

      - name: Test-19.06-on-ubuntu:18.04
        run: docker run rock-osdeps/18.04 /bin/bash -c "/home/docker/test_release.sh master-19.06"

      - name: Test-20.01-on-ubuntu:18.04
        run: docker run rock-osdeps/18.04 /bin/bash -c "/home/docker/test_release.sh master-20.01"

      - name: Test-20.06-on-ubuntu:18.04
        run: docker run rock-osdeps/18.04 /bin/bash -c "/home/docker/test_release.sh master-20.06"

      - name: Test-20.10-on-ubuntu:18.04
        run: docker run rock-osdeps/18.04 /bin/bash -c "/home/docker/test_release.sh master-20.10"

